Fix nightly clippy errors (#1074)
* Allow `clippy::nonminimal_bool` for `call()`

The `if !#any_message_accept_payment {` can result in `if !{`,
which causes clippy to complain.

* Fix `clippy::map_flatten` with `.and_then(…)`

The specific error was:

	error: called `map(..).flatten()` on an `Option`
	= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten

* Fix `clippy:map_flatten` with `.flat_map(…)`

The specific error was:

	error: called `map(..).flatten()` on an `Iterator`
	= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten