Fix nightly clippy errors (#760)
* Fix `clippy:wrong_self_convention`

error: methods with the following characteristics: (`to_*` and `self` type is `Copy`) usually take `self` by value
   --> crates/primitives/src/key.rs:172:21
    |
172 |     pub fn to_bytes(&self) -> [u8; 32] {
    |                     ^^^^^
    |
    = note: `-D clippy::wrong-self-convention` implied by `-D warnings`
    = help: consider choosing a less ambiguous name
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention

error: methods with the following characteristics: (`to_*` and `self` type is `Copy`) usually take `self` by value
   --> crates/primitives/src/key.rs:186:29
    |
186 |     fn to_bytes_be_fallback(&self) -> [u8; 32] {
    |                             ^^^^^
    |
    = help: consider choosing a less ambiguous name
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention

* Fix `clippy:branches_sharing_code` for `bitvec`

error: all if blocks contain the same code at the end
   --> crates/storage/src/collections/bitvec/mod.rs:280:9
    |
280 | /             *self.len += 1;
281 | |             if value {
282 | |                 self.last_mut()
283 | |                     .expect("must have at least a valid bit in this case")
284 | |                     .set()
285 | |             }
286 | |         }
    | |_________^
    |
    = note: `-D clippy::branches-sharing-code` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#branches_sharing_code

* Fix `clippy:branches_sharing_code` for `stash`

error: all if blocks contain the same code at the start
   --> crates/storage/src/collections/stash/mod.rs:308:9
    |
308 | /         if prev_vacant == next_vacant {
309 | |             // There is only one other vacant entry left.
310 | |             // We can update the single vacant entry in a single look-up.
311 | |             let entry = self
...   |
315 | |                 .flatten()
316 | |                 .expect("`prev` must point to an existing entry at this point");
    | |________________________________________________________________________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#branches_sharing_code

* Add benchmark for "Fix `clippy:wrong_self_convention`"

* Revert "Add benchmark for "Fix `clippy:wrong_self_convention`""

This reverts commit 9fabbfd1607d03c68117ee9d39ab26b79b4c70fe.

* Remove empty line