Implement getters akin to EVM opcodes (#2719)
* implement `gas_limit` host fn

* add tests for `gas_limit` host fn

* remove off-chain tests for `gas_limit`

* add changes to changelog

* run formatting

* fix error in env-access ui test

* run formatting

* Apply suggestions from code review

Co-authored-by: Michael Müller <mich@elmueller.net>

* update versions in gas and misc hostfns internal tests

* impl  and test `chain_id` hostfn

* add entry to changelog

* impl  and test `balance_of` host fn

* impl and test `base_fee`

* impl and test `origin`

* impl and test `code_size` hostfn

* impl and test `block_author`

* impl and test `block_hash`

* run formatting

* fix some ci/cd issues

* fix error[E0412]: cannot find type  in this scope

* fix docs for chain_id

* fix `block_hash` doc error

* run formatting

* fix merge errors on changelog

* start refactoring block_hash

* finish block_hash refatoring

* use take_encoded to avoid allocation

* run formatting

---------

Co-authored-by: Michael Müller <mich@elmueller.net>