Run `clippy` in stable
We run into

	error[E0514]: found crate `core` compiled by an incompatible version of rustc

otherwise, due to the e2e tests that build
the contract in stable.